Shumin/map service
shineyruan/particle_filter pull request #3
Opened 2021-10-29 19:55 UTC by Shumin326

* Changed to using our map service as default so the map can be updated periodically. 
* It has the feature that the **self-hold map variable will be updated only if received message is different**.
* If our map service is not launched, it will switch to using ROS map_server and get a static map. So if you still want to use the static map, launch ROS map_server along with the particle filter.

**TEST COVERAGE**: It now can get the initial map from our map_service and do localization well. However, when map is updated, node will throw error. It's due to that a lot of other variables dependent on the occupancy map need to be updated(not completely clear yet).

2021-10-29 20:08 UTC, shineyruan requested changes

2021-10-29 20:08 UTC, shineyruan commented on launch/localize_mapservice_viz.launch
> +  <include file="$(find particle_filter)/launch/localize_mapservice.launch"/>
Same problem as above

2021-10-29 20:08 UTC, shineyruan commented on launch/localize_mapservice.launch
> +	<node pkg="map_service" type="revit_map_test" name="revit_map_test"/>
**Please avoid writing launch files that directly depends on `map_service` in this rospkg**, as this rospkg is meant to run onboard and `map_service` is meant to run on central server (handles multi-agent map merging as well in future). Normally they will be placed in different ROS workspaces. 

Writing a launch file that runs particle filter without any map is sufficient. We can manually run the map server in another terminal.

2021-10-29 20:11 UTC, shineyruan commented
Another quick question --- is the particle filter ready to subscribe `map_service`? It seems to me that this feature is not ready yet due to the crash on map updates, as reflected in your code comments.

2021-10-30 01:37 UTC, Shumin326 commented
> Another quick question --- is the particle filter ready to subscribe `map_service`? It seems to me that this feature is not ready yet due to the crash on map updates, as reflected in your code comments.

Fixed, thanks!

2021-10-30 04:14 UTC, shineyruan requested changes

2021-10-30 04:14 UTC, shineyruan commented on scripts/particle_filter.py
> +        self.state_lock.release()
Should not be inside the if statement

2021-10-31 01:21 UTC, Shumin326 commented on scripts/particle_filter.py
> +        self.state_lock.release()
Good catch!

2021-10-31 01:58 UTC, shineyruan approved these changes
lgtm

2021-10-31 01:59 UTC, merged